services:
  starter-worker:
    build:
      context: ../../
      dockerfile: apps/worker/Dockerfile
    networks:
      - turborepo-astro-starter-network
    restart: unless-stopped

networks:
  turborepo-astro-starter-network:
    external: true
