services:
  starter-backend:
    # Jan 29 2026
    image: ghcr.io/get-convex/convex-backend:aef0568827a4d1b9a3a6a8c45653567af54b59b9
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${PORT:-3210}:3210"
      - "${SITE_PROXY_PORT:-3211}:3211"
    volumes:
      - /var/lib/turborepo-astro-starter/convex-data:/convex/data

    healthcheck:
      test: curl -f http://localhost:3210/version
      interval: 5s
      start_period: 10s

    networks:
      - turborepo-astro-starter-network
    restart: unless-stopped

  starter-dashboard:
    image: ghcr.io/get-convex/convex-dashboard:aef0568827a4d1b9a3a6a8c45653567af54b59b9
    stop_grace_period: 10s
    stop_signal: SIGINT
    ports:
      - "${DASHBOARD_PORT:-6791}:6791"
    depends_on:
      starter-backend:
        condition: service_healthy
    networks:
      - turborepo-astro-starter-network
    restart: unless-stopped

networks:
  turborepo-astro-starter-network:
    external: true
